
/*
	File generated by NetTiers templates [www.nettiers.net]
	Generated on : 6 Kasım 2018 Salı
	Important: Do not modify this file. Edit the file Town.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using Ekip.Framework.Entities.Validation;
#endregion

namespace Ekip.Framework.Entities
{
	///<summary>
	/// An object representation of the 'Town' table. [No description found the database]	
	///</summary>
	[DataContract]
	[DataObject, CLSCompliant(true)]
	public abstract partial class TownBase : EntityBase, ITown, IEntityId<TownKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		[DataMember]
		private TownEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		[DataMember]
		private TownEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private TownEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		private TList<Town> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		public event TownEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		public event TownEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="TownBase"/> instance.
		///</summary>
		public TownBase()
		{
			this.entityData = new TownEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="TownBase"/> instance.
		///</summary>
		///<param name="_rowNumber"></param>
		///<param name="_adminId"></param>
		///<param name="_objectId"></param>
		///<param name="_parentId"></param>
		///<param name="_provinceId"></param>
		///<param name="_townName"></param>
		///<param name="_longitude"></param>
		///<param name="_latitude"></param>
		///<param name="_type"></param>
		///<param name="_createDate"></param>
		///<param name="_createTime"></param>
		///<param name="_updateDate"></param>
		///<param name="_updateTime"></param>
		public TownBase(System.Int32 _rowNumber, System.Int64 _adminId, System.Int64 _objectId, 
			System.Int64 _parentId, System.Int32 _provinceId, System.String _townName, System.String _longitude, System.String _latitude, 
			System.Int32 _type, System.DateTime _createDate, System.TimeSpan _createTime, System.DateTime? _updateDate, 
			System.TimeSpan? _updateTime)
		{
			this.entityData = new TownEntityData();
			this.backupData = null;

			this.RowNumber = _rowNumber;
			this.AdminId = _adminId;
			this.ObjectId = _objectId;
			this.ParentId = _parentId;
			this.ProvinceId = _provinceId;
			this.TownName = _townName;
			this.Longitude = _longitude;
			this.Latitude = _latitude;
			this.Type = _type;
			this.CreateDate = _createDate;
			this.CreateTime = _createTime;
			this.UpdateDate = _updateDate;
			this.UpdateTime = _updateTime;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="Town"/> instance.
		///</summary>
		///<param name="_rowNumber"></param>
		///<param name="_adminId"></param>
		///<param name="_objectId"></param>
		///<param name="_parentId"></param>
		///<param name="_provinceId"></param>
		///<param name="_townName"></param>
		///<param name="_longitude"></param>
		///<param name="_latitude"></param>
		///<param name="_type"></param>
		///<param name="_createDate"></param>
		///<param name="_createTime"></param>
		///<param name="_updateDate"></param>
		///<param name="_updateTime"></param>
		public static Town CreateTown(System.Int32 _rowNumber, System.Int64 _adminId, System.Int64 _objectId, 
			System.Int64 _parentId, System.Int32 _provinceId, System.String _townName, System.String _longitude, System.String _latitude, 
			System.Int32 _type, System.DateTime _createDate, System.TimeSpan _createTime, System.DateTime? _updateDate, 
			System.TimeSpan? _updateTime)
		{
			Town newTown = new Town();
			newTown.RowNumber = _rowNumber;
			newTown.AdminId = _adminId;
			newTown.ObjectId = _objectId;
			newTown.ParentId = _parentId;
			newTown.ProvinceId = _provinceId;
			newTown.TownName = _townName;
			newTown.Longitude = _longitude;
			newTown.Latitude = _latitude;
			newTown.Type = _type;
			newTown.CreateDate = _createDate;
			newTown.CreateTime = _createTime;
			newTown.UpdateDate = _updateDate;
			newTown.UpdateTime = _updateTime;
			return newTown;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the Id property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int32 Id
		{
			get
			{
				return this.entityData.Id; 
			}
			
			set
			{
				if (this.entityData.Id == value)
					return;
				
                OnPropertyChanging("Id");                    
				OnColumnChanging(TownColumn.Id, this.entityData.Id);
				this.entityData.Id = value;
				this.EntityId.Id = value;
				if ( !this._deserializing && this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TownColumn.Id, this.entityData.Id);
				OnPropertyChanged("Id");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the RowNumber property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 RowNumber
		{
			get
			{
				return this.entityData.RowNumber; 
			}
			
			set
			{
				if (this.entityData.RowNumber == value)
					return;
				
                OnPropertyChanging("RowNumber");                    
				OnColumnChanging(TownColumn.RowNumber, this.entityData.RowNumber);
				this.entityData.RowNumber = value;
				if ( !this._deserializing && this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TownColumn.RowNumber, this.entityData.RowNumber);
				OnPropertyChanged("RowNumber");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the AdminId property. 
		///		
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int64 AdminId
		{
			get
			{
				return this.entityData.AdminId; 
			}
			
			set
			{
				if (this.entityData.AdminId == value)
					return;
				
                OnPropertyChanging("AdminId");                    
				OnColumnChanging(TownColumn.AdminId, this.entityData.AdminId);
				this.entityData.AdminId = value;
				if ( !this._deserializing && this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TownColumn.AdminId, this.entityData.AdminId);
				OnPropertyChanged("AdminId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ObjectId property. 
		///		
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int64 ObjectId
		{
			get
			{
				return this.entityData.ObjectId; 
			}
			
			set
			{
				if (this.entityData.ObjectId == value)
					return;
				
                OnPropertyChanging("ObjectId");                    
				OnColumnChanging(TownColumn.ObjectId, this.entityData.ObjectId);
				this.entityData.ObjectId = value;
				if ( !this._deserializing && this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TownColumn.ObjectId, this.entityData.ObjectId);
				OnPropertyChanged("ObjectId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ParentId property. 
		///		
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int64 ParentId
		{
			get
			{
				return this.entityData.ParentId; 
			}
			
			set
			{
				if (this.entityData.ParentId == value)
					return;
				
                OnPropertyChanging("ParentId");                    
				OnColumnChanging(TownColumn.ParentId, this.entityData.ParentId);
				this.entityData.ParentId = value;
				if ( !this._deserializing && this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TownColumn.ParentId, this.entityData.ParentId);
				OnPropertyChanged("ParentId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ProvinceId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 ProvinceId
		{
			get
			{
				return this.entityData.ProvinceId; 
			}
			
			set
			{
				if (this.entityData.ProvinceId == value)
					return;
				
                OnPropertyChanging("ProvinceId");                    
				OnColumnChanging(TownColumn.ProvinceId, this.entityData.ProvinceId);
				this.entityData.ProvinceId = value;
				if ( !this._deserializing && this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TownColumn.ProvinceId, this.entityData.ProvinceId);
				OnPropertyChanged("ProvinceId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the TownName property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 250)]
		public virtual System.String TownName
		{
			get
			{
				return this.entityData.TownName; 
			}
			
			set
			{
				if (this.entityData.TownName == value)
					return;
				
                OnPropertyChanging("TownName");                    
				OnColumnChanging(TownColumn.TownName, this.entityData.TownName);
				this.entityData.TownName = value;
				if ( !this._deserializing && this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TownColumn.TownName, this.entityData.TownName);
				OnPropertyChanged("TownName");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Longitude property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 10)]
		public virtual System.String Longitude
		{
			get
			{
				return this.entityData.Longitude; 
			}
			
			set
			{
				if (this.entityData.Longitude == value)
					return;
				
                OnPropertyChanging("Longitude");                    
				OnColumnChanging(TownColumn.Longitude, this.entityData.Longitude);
				this.entityData.Longitude = value;
				if ( !this._deserializing && this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TownColumn.Longitude, this.entityData.Longitude);
				OnPropertyChanged("Longitude");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Latitude property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 10)]
		public virtual System.String Latitude
		{
			get
			{
				return this.entityData.Latitude; 
			}
			
			set
			{
				if (this.entityData.Latitude == value)
					return;
				
                OnPropertyChanging("Latitude");                    
				OnColumnChanging(TownColumn.Latitude, this.entityData.Latitude);
				this.entityData.Latitude = value;
				if ( !this._deserializing && this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TownColumn.Latitude, this.entityData.Latitude);
				OnPropertyChanged("Latitude");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Type property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 Type
		{
			get
			{
				return this.entityData.Type; 
			}
			
			set
			{
				if (this.entityData.Type == value)
					return;
				
                OnPropertyChanging("Type");                    
				OnColumnChanging(TownColumn.Type, this.entityData.Type);
				this.entityData.Type = value;
				if ( !this._deserializing && this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TownColumn.Type, this.entityData.Type);
				OnPropertyChanged("Type");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CreateDate property. 
		///		
		/// </summary>
		/// <value>This type is date.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.DateTime CreateDate
		{
			get
			{
				return this.entityData.CreateDate; 
			}
			
			set
			{
				if (this.entityData.CreateDate == value)
					return;
				
                OnPropertyChanging("CreateDate");                    
				OnColumnChanging(TownColumn.CreateDate, this.entityData.CreateDate);
				this.entityData.CreateDate = value;
				if ( !this._deserializing && this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TownColumn.CreateDate, this.entityData.CreateDate);
				OnPropertyChanged("CreateDate");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CreateTime property. 
		///		
		/// </summary>
		/// <value>This type is time.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.TimeSpan CreateTime
		{
			get
			{
				return this.entityData.CreateTime; 
			}
			
			set
			{
				if (this.entityData.CreateTime == value)
					return;
				
                OnPropertyChanging("CreateTime");                    
				OnColumnChanging(TownColumn.CreateTime, this.entityData.CreateTime);
				this.entityData.CreateTime = value;
				if ( !this._deserializing && this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TownColumn.CreateTime, this.entityData.CreateTime);
				OnPropertyChanged("CreateTime");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the UpdateDate property. 
		///		
		/// </summary>
		/// <value>This type is date.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? UpdateDate
		{
			get
			{
				return this.entityData.UpdateDate; 
			}
			
			set
			{
				if (this.entityData.UpdateDate == value)
					return;
				
                OnPropertyChanging("UpdateDate");                    
				OnColumnChanging(TownColumn.UpdateDate, this.entityData.UpdateDate);
				this.entityData.UpdateDate = value;
				if ( !this._deserializing && this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TownColumn.UpdateDate, this.entityData.UpdateDate);
				OnPropertyChanged("UpdateDate");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the UpdateTime property. 
		///		
		/// </summary>
		/// <value>This type is time.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.TimeSpan? UpdateTime
		{
			get
			{
				return this.entityData.UpdateTime; 
			}
			
			set
			{
				if (this.entityData.UpdateTime == value)
					return;
				
                OnPropertyChanging("UpdateTime");                    
				OnColumnChanging(TownColumn.UpdateTime, this.entityData.UpdateTime);
				this.entityData.UpdateTime = value;
				if ( !this._deserializing && this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TownColumn.UpdateTime, this.entityData.UpdateTime);
				OnPropertyChanged("UpdateTime");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="Province"/>.
		/// </summary>
		/// <value>The source Province for ProvinceId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Province ProvinceIdSource
      	{
            get { return entityData.ProvinceIdSource; }
            set { entityData.ProvinceIdSource = value; }
      	}
		#endregion
		
		#region Children Collections
	
		/// <summary>
		///	Holds a collection of Neighborhood objects
		///	which are related to this object through the relation FK_Neighborhood_Town
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<Neighborhood> NeighborhoodCollection
		{
			get { return entityData.NeighborhoodCollection; }
			set { entityData.NeighborhoodCollection = value; }	
		}
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("TownName", "Town Name"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("TownName", "Town Name", 250));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("Longitude", "Longitude"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Longitude", "Longitude", 10));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("Latitude", "Latitude"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Latitude", "Latitude", 10));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "Town"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"Id", "RowNumber", "AdminId", "ObjectId", "ParentId", "ProvinceId", "TownName", "Longitude", "Latitude", "Type", "CreateDate", "CreateTime", "UpdateDate", "UpdateTime"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as TownEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (Town) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<Town>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as Town);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed Town Entity 
		///</summary>
		protected virtual Town Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			Town copy = new Town();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.Id = this.Id;
				copy.RowNumber = this.RowNumber;
				copy.AdminId = this.AdminId;
				copy.ObjectId = this.ObjectId;
				copy.ParentId = this.ParentId;
				copy.ProvinceId = this.ProvinceId;
				copy.TownName = this.TownName;
				copy.Longitude = this.Longitude;
				copy.Latitude = this.Latitude;
				copy.Type = this.Type;
				copy.CreateDate = this.CreateDate;
				copy.CreateTime = this.CreateTime;
				copy.UpdateDate = this.UpdateDate;
				copy.UpdateTime = this.UpdateTime;
			
			if (this.ProvinceIdSource != null && existingCopies.Contains(this.ProvinceIdSource))
				copy.ProvinceIdSource = existingCopies[this.ProvinceIdSource] as Province;
			else
				copy.ProvinceIdSource = MakeCopyOf(this.ProvinceIdSource, existingCopies) as Province;
		
			//deep copy nested objects
			copy.NeighborhoodCollection = (TList<Neighborhood>) MakeCopyOf(this.NeighborhoodCollection, existingCopies); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed Town Entity 
		///</summary>
		public virtual Town Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed Town Entity which is a deep copy of the current entity.
		///</summary>
		public virtual Town DeepCopy()
		{
			return EntityHelper.Clone<Town>(this as Town);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as TownEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new TownEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as TownEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(TownColumn column)
		{
			switch(column)
			{
					case TownColumn.Id:
					return entityData.Id != _originalData.Id;
					case TownColumn.RowNumber:
					return entityData.RowNumber != _originalData.RowNumber;
					case TownColumn.AdminId:
					return entityData.AdminId != _originalData.AdminId;
					case TownColumn.ObjectId:
					return entityData.ObjectId != _originalData.ObjectId;
					case TownColumn.ParentId:
					return entityData.ParentId != _originalData.ParentId;
					case TownColumn.ProvinceId:
					return entityData.ProvinceId != _originalData.ProvinceId;
					case TownColumn.TownName:
					return entityData.TownName != _originalData.TownName;
					case TownColumn.Longitude:
					return entityData.Longitude != _originalData.Longitude;
					case TownColumn.Latitude:
					return entityData.Latitude != _originalData.Latitude;
					case TownColumn.Type:
					return entityData.Type != _originalData.Type;
					case TownColumn.CreateDate:
					return entityData.CreateDate != _originalData.CreateDate;
					case TownColumn.CreateTime:
					return entityData.CreateTime != _originalData.CreateTime;
					case TownColumn.UpdateDate:
					return entityData.UpdateDate != _originalData.UpdateDate;
					case TownColumn.UpdateTime:
					return entityData.UpdateTime != _originalData.UpdateTime;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< TownColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.Id != _originalData.Id;
			result = result || entityData.RowNumber != _originalData.RowNumber;
			result = result || entityData.AdminId != _originalData.AdminId;
			result = result || entityData.ObjectId != _originalData.ObjectId;
			result = result || entityData.ParentId != _originalData.ParentId;
			result = result || entityData.ProvinceId != _originalData.ProvinceId;
			result = result || entityData.TownName != _originalData.TownName;
			result = result || entityData.Longitude != _originalData.Longitude;
			result = result || entityData.Latitude != _originalData.Latitude;
			result = result || entityData.Type != _originalData.Type;
			result = result || entityData.CreateDate != _originalData.CreateDate;
			result = result || entityData.CreateTime != _originalData.CreateTime;
			result = result || entityData.UpdateDate != _originalData.UpdateDate;
			result = result || entityData.UpdateTime != _originalData.UpdateTime;
			return result;
		}	
		
		///<summary>
		///  Returns a Town Entity with the original data.
		///</summary>
		public Town GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateTown(
				_originalData.RowNumber,
				_originalData.AdminId,
				_originalData.ObjectId,
				_originalData.ParentId,
				_originalData.ProvinceId,
				_originalData.TownName,
				_originalData.Longitude,
				_originalData.Latitude,
				_originalData.Type,
				_originalData.CreateDate,
				_originalData.CreateTime,
				_originalData.UpdateDate,
				_originalData.UpdateTime
				);
				
			return (Town)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="TownBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is TownBase)
				return ValueEquals(this, (TownBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="TownBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.Id.GetHashCode() ^ 
					this.RowNumber.GetHashCode() ^ 
					this.AdminId.GetHashCode() ^ 
					this.ObjectId.GetHashCode() ^ 
					this.ParentId.GetHashCode() ^ 
					this.ProvinceId.GetHashCode() ^ 
					this.TownName.GetHashCode() ^ 
					this.Longitude.GetHashCode() ^ 
					this.Latitude.GetHashCode() ^ 
					this.Type.GetHashCode() ^ 
					this.CreateDate.GetHashCode() ^ 
					this.CreateTime.GetHashCode() ^ 
					((this.UpdateDate == null) ? string.Empty : this.UpdateDate.ToString()).GetHashCode() ^ 
					((this.UpdateTime == null) ? string.Empty : this.UpdateTime.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="TownBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(TownBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="TownBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="TownBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="TownBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(TownBase Object1, TownBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.Id != Object2.Id)
				equal = false;
			if (Object1.RowNumber != Object2.RowNumber)
				equal = false;
			if (Object1.AdminId != Object2.AdminId)
				equal = false;
			if (Object1.ObjectId != Object2.ObjectId)
				equal = false;
			if (Object1.ParentId != Object2.ParentId)
				equal = false;
			if (Object1.ProvinceId != Object2.ProvinceId)
				equal = false;
			if (Object1.TownName != Object2.TownName)
				equal = false;
			if (Object1.Longitude != Object2.Longitude)
				equal = false;
			if (Object1.Latitude != Object2.Latitude)
				equal = false;
			if (Object1.Type != Object2.Type)
				equal = false;
			if (Object1.CreateDate != Object2.CreateDate)
				equal = false;
			if (Object1.CreateTime != Object2.CreateTime)
				equal = false;
			if ( Object1.UpdateDate != null && Object2.UpdateDate != null )
			{
				if (Object1.UpdateDate != Object2.UpdateDate)
					equal = false;
			}
			else if (Object1.UpdateDate == null ^ Object2.UpdateDate == null )
			{
				equal = false;
			}
			if ( Object1.UpdateTime != null && Object2.UpdateTime != null )
			{
				if (Object1.UpdateTime != Object2.UpdateTime)
					equal = false;
			}
			else if (Object1.UpdateTime == null ^ Object2.UpdateTime == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((TownBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static TownComparer GetComparer()
        {
            return new TownComparer();
        }
        */

        // Comparer delegates back to Town
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(Town rhs, TownColumn which)
        {
            switch (which)
            {
            	
            	
            	case TownColumn.Id:
            		return this.Id.CompareTo(rhs.Id);
            		
            		                 
            	
            	
            	case TownColumn.RowNumber:
            		return this.RowNumber.CompareTo(rhs.RowNumber);
            		
            		                 
            	
            	
            	case TownColumn.AdminId:
            		return this.AdminId.CompareTo(rhs.AdminId);
            		
            		                 
            	
            	
            	case TownColumn.ObjectId:
            		return this.ObjectId.CompareTo(rhs.ObjectId);
            		
            		                 
            	
            	
            	case TownColumn.ParentId:
            		return this.ParentId.CompareTo(rhs.ParentId);
            		
            		                 
            	
            	
            	case TownColumn.ProvinceId:
            		return this.ProvinceId.CompareTo(rhs.ProvinceId);
            		
            		                 
            	
            	
            	case TownColumn.TownName:
            		return this.TownName.CompareTo(rhs.TownName);
            		
            		                 
            	
            	
            	case TownColumn.Longitude:
            		return this.Longitude.CompareTo(rhs.Longitude);
            		
            		                 
            	
            	
            	case TownColumn.Latitude:
            		return this.Latitude.CompareTo(rhs.Latitude);
            		
            		                 
            	
            	
            	case TownColumn.Type:
            		return this.Type.CompareTo(rhs.Type);
            		
            		                 
            	
            	
            	case TownColumn.CreateDate:
            		return this.CreateDate.CompareTo(rhs.CreateDate);
            		
            		                 
            	
            	
            	case TownColumn.CreateTime:
            		return this.CreateTime.CompareTo(rhs.CreateTime);
            		
            		                 
            	
            	
            	case TownColumn.UpdateDate:
            		return this.UpdateDate.Value.CompareTo(rhs.UpdateDate.Value);
            		
            		                 
            	
            	
            	case TownColumn.UpdateTime:
            		return this.UpdateTime.Value.CompareTo(rhs.UpdateTime.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<TownKey> Members
		
		// member variable for the EntityId property
		private TownKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual TownKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new TownKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) ]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("Town")
					.Append("|").Append( this.Id.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{15}{14}- Id: {0}{14}- RowNumber: {1}{14}- AdminId: {2}{14}- ObjectId: {3}{14}- ParentId: {4}{14}- ProvinceId: {5}{14}- TownName: {6}{14}- Longitude: {7}{14}- Latitude: {8}{14}- Type: {9}{14}- CreateDate: {10}{14}- CreateTime: {11}{14}- UpdateDate: {12}{14}- UpdateTime: {13}{14}{16}", 
				this.Id,
				this.RowNumber,
				this.AdminId,
				this.ObjectId,
				this.ParentId,
				this.ProvinceId,
				this.TownName,
				this.Longitude,
				this.Latitude,
				this.Type,
				this.CreateDate,
				this.CreateTime,
				(this.UpdateDate == null) ? string.Empty : this.UpdateDate.ToString(),
				(this.UpdateTime == null) ? string.Empty : this.UpdateTime.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'Town' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[DataContract]
	internal protected class TownEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// Id : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Town"</remarks>
		[DataMember]
		public System.Int32 Id;
			
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// RowNumber : 
		/// </summary>
		[DataMember]
		public System.Int32 RowNumber = (int)0;
		
		/// <summary>
		/// AdminId : 
		/// </summary>
		[DataMember]
		public System.Int64 AdminId = (long)0;
		
		/// <summary>
		/// ObjectId : 
		/// </summary>
		[DataMember]
		public System.Int64 ObjectId = (long)0;
		
		/// <summary>
		/// ParentId : 
		/// </summary>
		[DataMember]
		public System.Int64 ParentId = (long)0;
		
		/// <summary>
		/// ProvinceId : 
		/// </summary>
		[DataMember]
		public System.Int32 ProvinceId = (int)0;
		
		/// <summary>
		/// TownName : 
		/// </summary>
		[DataMember]
		public System.String TownName = string.Empty;
		
		/// <summary>
		/// Longitude : 
		/// </summary>
		[DataMember]
		public System.String Longitude = string.Empty;
		
		/// <summary>
		/// Latitude : 
		/// </summary>
		[DataMember]
		public System.String Latitude = string.Empty;
		
		/// <summary>
		/// Type : 
		/// </summary>
		[DataMember]
		public System.Int32 Type = (int)1;
		
		/// <summary>
		/// CreateDate : 
		/// </summary>
		[DataMember]
		public System.DateTime CreateDate = DateTime.Now;
		
		/// <summary>
		/// CreateTime : 
		/// </summary>
		[DataMember]
		public System.TimeSpan CreateTime = new TimeSpan(1,0,0,0,0);
		
		/// <summary>
		/// UpdateDate : 
		/// </summary>
		[DataMember]
		public System.DateTime? UpdateDate = null;
		
		/// <summary>
		/// UpdateTime : 
		/// </summary>
		[DataMember]
		public System.TimeSpan? UpdateTime = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private Province _provinceIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Province"/>.
		/// </summary>
		/// <value>The source Province for ProvinceId.</value>
		[DataMember]
		[Browsable(false)]
		public virtual Province ProvinceIdSource
      	{
            get { return this._provinceIdSource; }
            set { this._provinceIdSource = value; }
      	}
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#region NeighborhoodCollection
		
		private TList<Neighborhood> _neighborhoodTownId;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _neighborhoodTownId
		/// </summary>
		[DataMember]
		public TList<Neighborhood> NeighborhoodCollection
		{
			get
			{
				if (_neighborhoodTownId == null)
				{
				_neighborhoodTownId = new TList<Neighborhood>();
				}
	
				return _neighborhoodTownId;
			}
			set { _neighborhoodTownId = value; }
		}
		
		#endregion

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			TownEntityData _tmp = new TownEntityData();
						
			_tmp.Id = this.Id;
			
			_tmp.RowNumber = this.RowNumber;
			_tmp.AdminId = this.AdminId;
			_tmp.ObjectId = this.ObjectId;
			_tmp.ParentId = this.ParentId;
			_tmp.ProvinceId = this.ProvinceId;
			_tmp.TownName = this.TownName;
			_tmp.Longitude = this.Longitude;
			_tmp.Latitude = this.Latitude;
			_tmp.Type = this.Type;
			_tmp.CreateDate = this.CreateDate;
			_tmp.CreateTime = this.CreateTime;
			_tmp.UpdateDate = this.UpdateDate;
			_tmp.UpdateTime = this.UpdateTime;
			
			#region Source Parent Composite Entities
			if (this.ProvinceIdSource != null)
				_tmp.ProvinceIdSource = MakeCopyOf(this.ProvinceIdSource) as Province;
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this._neighborhoodTownId != null)
				_tmp.NeighborhoodCollection = (TList<Neighborhood>) MakeCopyOf(this.NeighborhoodCollection); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			TownEntityData _tmp = new TownEntityData();
						
			_tmp.Id = this.Id;
			
			_tmp.RowNumber = this.RowNumber;
			_tmp.AdminId = this.AdminId;
			_tmp.ObjectId = this.ObjectId;
			_tmp.ParentId = this.ParentId;
			_tmp.ProvinceId = this.ProvinceId;
			_tmp.TownName = this.TownName;
			_tmp.Longitude = this.Longitude;
			_tmp.Latitude = this.Latitude;
			_tmp.Type = this.Type;
			_tmp.CreateDate = this.CreateDate;
			_tmp.CreateTime = this.CreateTime;
			_tmp.UpdateDate = this.UpdateDate;
			_tmp.UpdateTime = this.UpdateTime;
			
			#region Source Parent Composite Entities
			if (this.ProvinceIdSource != null && existingCopies.Contains(this.ProvinceIdSource))
				_tmp.ProvinceIdSource = existingCopies[this.ProvinceIdSource] as Province;
			else
				_tmp.ProvinceIdSource = MakeCopyOf(this.ProvinceIdSource, existingCopies) as Province;
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			_tmp.NeighborhoodCollection = (TList<Neighborhood>) MakeCopyOf(this.NeighborhoodCollection, existingCopies); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false)]
		[DataMember]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region DataContract serialization
		
		bool _deserializing = false;
		
		/// <summary>
		/// Called before deserializing the type.
		/// </summary>
		[OnDeserializingAttribute]
		private void Initialize_BeforeDeserializing(StreamingContext context)
		{
			this._deserializing = true;
		
			this.entityData = new TownEntityData();
			this.backupData = null;
			
			AddValidationRules();
		}
		
		/// <summary>
		/// Called after deserializing the type.
		/// </summary>
		[OnDeserializedAttribute ]
		private void Initialize_Deserialized(StreamingContext context)
		{
			this._deserializing = false;
		}
				
		#endregion
		
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="TownColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(TownColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="TownColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(TownColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="TownColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(TownColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				TownEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new TownEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="TownColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(TownColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				TownEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new TownEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region TownEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="Town"/> object.
	/// </remarks>
	public class TownEventArgs : System.EventArgs
	{
		private TownColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the TownEventArgs class.
		///</summary>
		public TownEventArgs(TownColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the TownEventArgs class.
		///</summary>
		public TownEventArgs(TownColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The TownColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="TownColumn" />
		public TownColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all Town related events.
	///</summary>
	public delegate void TownEventHandler(object sender, TownEventArgs e);
	
	#region TownComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class TownComparer : System.Collections.Generic.IComparer<Town>
	{
		TownColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:TownComparer"/> class.
        /// </summary>
		public TownComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:TownComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public TownComparer(TownColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="Town"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="Town"/> to compare.</param>
        /// <param name="b">The second <c>Town</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(Town a, Town b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(Town entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(Town a, Town b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public TownColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region TownKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="Town"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class TownKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the TownKey class.
		/// </summary>
		public TownKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the TownKey class.
		/// </summary>
		public TownKey(TownBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.Id = entity.Id;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the TownKey class.
		/// </summary>
		public TownKey(System.Int32 _ıd)
		{
			#region Init Properties

			this.Id = _ıd;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private TownBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public TownBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the Id property
		private System.Int32 _ıd;
		
		/// <summary>
		/// Gets or sets the Id property.
		/// </summary>
		public System.Int32 Id
		{
			get { return _ıd; }
			set
			{
				if ( this.Entity != null )
					this.Entity.Id = value;
				
				_ıd = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				Id = ( values["Id"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["Id"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("Id", Id);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("Id: {0}{1}",
								Id,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region TownColumn Enum
	
	/// <summary>
	/// Enumerate the Town columns.
	/// </summary>
	[Serializable]
	public enum TownColumn : int
	{
		/// <summary>
		/// Id : 
		/// </summary>
		[EnumTextValue("Id")]
		[ColumnEnum("Id", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		Id = 1,
		/// <summary>
		/// RowNumber : 
		/// </summary>
		[EnumTextValue("Row Number")]
		[ColumnEnum("RowNumber", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		RowNumber = 2,
		/// <summary>
		/// AdminId : 
		/// </summary>
		[EnumTextValue("Admin Id")]
		[ColumnEnum("AdminId", typeof(System.Int64), System.Data.DbType.Int64, false, false, false)]
		AdminId = 3,
		/// <summary>
		/// ObjectId : 
		/// </summary>
		[EnumTextValue("Object Id")]
		[ColumnEnum("ObjectId", typeof(System.Int64), System.Data.DbType.Int64, false, false, false)]
		ObjectId = 4,
		/// <summary>
		/// ParentId : 
		/// </summary>
		[EnumTextValue("Parent Id")]
		[ColumnEnum("ParentId", typeof(System.Int64), System.Data.DbType.Int64, false, false, false)]
		ParentId = 5,
		/// <summary>
		/// ProvinceId : 
		/// </summary>
		[EnumTextValue("Province Id")]
		[ColumnEnum("ProvinceId", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		ProvinceId = 6,
		/// <summary>
		/// TownName : 
		/// </summary>
		[EnumTextValue("Town Name")]
		[ColumnEnum("TownName", typeof(System.String), System.Data.DbType.String, false, false, false, 250)]
		TownName = 7,
		/// <summary>
		/// Longitude : 
		/// </summary>
		[EnumTextValue("Longitude")]
		[ColumnEnum("Longitude", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 10)]
		Longitude = 8,
		/// <summary>
		/// Latitude : 
		/// </summary>
		[EnumTextValue("Latitude")]
		[ColumnEnum("Latitude", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 10)]
		Latitude = 9,
		/// <summary>
		/// Type : 
		/// </summary>
		[EnumTextValue("Type")]
		[ColumnEnum("Type", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		Type = 10,
		/// <summary>
		/// CreateDate : 
		/// </summary>
		[EnumTextValue("Create Date")]
		[ColumnEnum("CreateDate", typeof(System.DateTime), System.Data.DbType.Date, false, false, false)]
		CreateDate = 11,
		/// <summary>
		/// CreateTime : 
		/// </summary>
		[EnumTextValue("Create Time")]
		[ColumnEnum("CreateTime", typeof(System.TimeSpan), System.Data.DbType.Time, false, false, false)]
		CreateTime = 12,
		/// <summary>
		/// UpdateDate : 
		/// </summary>
		[EnumTextValue("Update Date")]
		[ColumnEnum("UpdateDate", typeof(System.DateTime), System.Data.DbType.Date, false, false, true)]
		UpdateDate = 13,
		/// <summary>
		/// UpdateTime : 
		/// </summary>
		[EnumTextValue("Update Time")]
		[ColumnEnum("UpdateTime", typeof(System.TimeSpan), System.Data.DbType.Time, false, false, true)]
		UpdateTime = 14
	}//End enum

	#endregion TownColumn Enum

} // end namespace
